### PR TITLE
Unity update

### PR DESCRIPTION
**Pull request by trond**
Upgraded Unity project to 5.2.2, and enabled .meta-files and re-linked the example script in the example scene so the project works out of the box.

### CODE REVIEW

**Comment by speps** [comment]
This is great, however, I would like to keep support Unity 4 for a while as it seems some people are using it. I'll get your changes and then move them to a different folder. Thanks for your PR! :)

**Comment by trond** [comment]
Sorry, yeah, that makes a lot of sense to keep it working with Unity4. I would still suggest adding the .meta-files to the project and switching to "force text" asset serialization, as it works better with version control. Currently the script link in the example scene is broken, so it doesn't work without some user fixup.

**Comment by Skybladev2** [comment]
Maybe it's better to make "Unity4" branch/label to keep Unity 4 support, but update "master" to the latest Unity release?

**Comment by speps** [comment]
Code is exactly the same the 2 versions, only the way the Unity project is
setup differs so it wouldn't make sense to have a separate branch.

**Comment by trond** [comment]
Enabling (and committing) .meta-files for the current Unity4-compatible project will fix the broken script link and should also keep working in Unity5. Enabling "force text" is not strictly necessary, but it plays better with version control as it's possible to see textual diffs when scene/prefab changes are made, and also that should not break Unity5-compatibility.

**Comment by speps** [comment]
Unity 5 has a different structure for plugins, it doesn't rely on
x86/x86_64 folders anymore but on the .meta for the plugin. So it would
need to be a different project for this reason not the meta files or force
text options :)

**Comment by Skybladev2** [comment]
Hmm, maybe separate project is not a bad idea... I vote for it.

**Comment by trond** [comment]
I see, yeah, that makes sense - my main point was to enable .meta-files to fix the broken example script link, which would apply to both U4 and U5 - I didn't think about the platform DLL stuff :)

**Comment by maakep** [comment]
I can't seem to get the controllers to work in my build (windows). They work perfectly in the Unity editor but when building nothing registers. Any ideas? Is it because of the old way: "Plugins/x86" etc? I had to delete the 32 bit because Unity complained about conflicting sources or something similar when trying to build. Any ideas?

**Comment by speps** [comment]
Is that for Unity 4 or 5?

**Comment by maakep** [comment]
That'd be 5!

**Comment by speps** [comment]
Okay, I might have a look tonight.

**Comment by maakep** [comment]
I'll try providing more information as well. Thanks

**Comment by pedro15** [comment]
I can't complie with unity 5.6. 

> error CS1704: An assembly with the same name `XInputDotNetPure' has already been imported. Consider removing one of the references or sign the assembly
> Assets/Plugins/x86/XInputDotNetPure.dll (Location of the symbol related to previous error)
> Assets/Plugins/x86_64/XInputDotNetPure.dll (Location of the symbol related to previous error)
> 
> Compilation failed: 1 error(s), 0 warnings

**Comment by maakep** [comment]
Yeah, that's the error I got as well. I removed the error by removing the `/x86/` folder and moved the `x86_64` folder to `/Assets/` but it seems to not work properly after building due to this. I'm guessing that's the cause, sounds resonable, hehe.

**Comment by speps** [comment]
I am fixing this error right now so you don't need to do anything.

**Comment by speps** [comment]
Alright, I upgraded to VS2015 and Unity 5.6.0. It should have the right .meta files now, I forgot to add them in the first place. Also, I added screenshots to show how to setup the plugin settings.

**Comment by maakep** [comment]
You're the best! Awesome work btw!

**Pull request closed without merging**
